export const hfGlobal = Object.freeze({
    /**
     * 난수 만들기 min~max
     * @param {number} min
     * @param {number} max
     * @returns number
     */
    randRange: (min, max) => {
        return min + Math.round(Math.random() * (max - min));
    },

    colorNames: Object.freeze([
        // White & Neutral
        'white', 'whitesmoke', 'gainsboro', 'lightgray', 'silver', 'darkgray', 'gray', 'dimgray', 'black',
        // Red & Pink
        'red', 'darkred', 'crimson', 'firebrick', 'indianred', 'lightcoral', 'salmon', 'darksalmon', 'lightsalmon',
        'coral', 'tomato', 'orangered', 'deeppink', 'hotpink', 'pink', 'lightpink', 'palevioletred', 'mediumvioletred',
        // Orange & Brown
        'orange', 'darkorange', 'gold', 'goldenrod', 'darkgoldenrod', 'peru', 'chocolate', 'sienna', 'brown',
        'maroon', 'saddlebrown', 'sandybrown', 'burlywood', 'tan', 'rosybrown', 'peachpuff', 'bisque', 'moccasin',
        // Yellow
        'yellow', 'lightyellow', 'lemonchiffon', 'lightgoldenrodyellow', 'papayawhip', 'mistyrose', 'cornsilk',
        'blanchedalmond', 'navajowhite', 'antiquewhite', 'wheat', 'oldlace', 'linen', 'seashell', 'snow',
        'honeydew', 'mintcream', 'azure', 'aliceblue', 'ghostwhite', 'ivory', 'floralwhite', 'beige', 'khaki', 'darkkhaki',
        // Green
        'green', 'darkgreen', 'forestgreen', 'seagreen', 'mediumseagreen', 'darkseagreen', 'lightseagreen',
        'palegreen', 'springgreen', 'mediumspringgreen', 'limegreen', 'lime', 'chartreuse', 'lawngreen',
        'greenyellow', 'yellowgreen', 'olivedrab', 'olive', 'darkolivegreen', 'teal', 'darkcyan',
        // Cyan & Blue
        'cyan', 'aqua', 'lightcyan', 'paleturquoise', 'aquamarine', 'turquoise', 'mediumturquoise',
        'darkturquoise', 'cadetblue', 'steelblue', 'lightsteelblue', 'powderblue', 'lightblue', 'skyblue',
        'lightskyblue', 'deepskyblue', 'dodgerblue', 'cornflowerblue', 'royalblue', 'blue', 'mediumblue',
        'darkblue', 'navy', 'midnightblue', 'slateblue', 'darkslateblue', 'mediumslateblue',
        // Purple & Magenta
        'purple', 'darkmagenta', 'darkorchid', 'mediumorchid', 'orchid', 'violet', 'plum', 'thistle',
        'lavender', 'fuchsia', 'magenta', 'blueviolet', 'indigo', 'rebeccapurple',
        // Additional Grays (Aliases)
        'grey', 'lightgrey', 'darkgrey', 'dimgrey', 'slategrey', 'darkslategrey', 'lightslategrey'
    ]),

    colorInfos: Object.freeze({
        "aliceblue": "#0f0700",
        "antiquewhite": "#051428",
        "aqua": "#ff0000",
        "aquamarine": "#80002b",
        "azure": "#0f0000",
        "beige": "#0a0a23",
        "bisque": "#001b3b",
        "black": "#ffffff",
        "blanchedalmond": "#001432",
        "blue": "#ffff00",
        "blueviolet": "#75d41d",
        "brown": "#5ad5d5",
        "burlywood": "#214778",
        "cadetblue": "#a0615f",
        "chartreuse": "#8000ff",
        "chocolate": "#2d96e1",
        "coral": "#0080af",
        "cornflowerblue": "#9b6a12",
        "cornsilk": "#000723",
        "crimson": "#23ebd3",
        "cyan": "#ff0000",
        "darkblue": "#ffff74",
        "darkcyan": "#ff7474",
        "darkgoldenrod": "#4779f4",
        "darkgray": "#565656",
        "darkgreen": "#ff9bff",
        "darkgrey": "#565656",
        "darkkhaki": "#444894",
        "darkmagenta": "#74ff74",
        "darkolivegreen": "#aa94d0",
        "darkorange": "#0073ff",
        "darkorchid": "#66cd33",
        "darkred": "#74ffff",
        "darksalmon": "#166985",
        "darkseagreen": "#704370",
        "darkslateblue": "#b7c274",
        "darkslategray": "#d0b0b0",
        "darkslategrey": "#d0b0b0",
        "darkturquoise": "#ff322e",
        "darkviolet": "#6bfff2",
        "deeppink": "#00eb6c",
        "deepskyblue": "#ff4000",
        "dimgray": "#969696",
        "dimgrey": "#969696",
        "dodgerblue": "#e16f00",
        "firebrick": "#4d3ddc",
        "floralwhite": "#00050f",
        "forestgreen": "#dd74dd",
        "fuchsia": "#00ff00",
        "gainsboro": "#232323",
        "ghostwhite": "#070700",
        "gold": "#0028ff",
        "goldenrod": "#215a3f",
        "gray": "#7f7f7f",
        "green": "#ff7f7f",
        "greenyellow": "#5200d0",
        "grey": "#7f7f7f",
        "honeydew": "#0f000f",
        "hotpink": "#00964b",
        "indianred": "#32a3a3",
        "indigo": "#b4ff7d",
        "ivory": "#00000f",
        "khaki": "#0f1973",
        "lavender": "#191905",
        "lavenderblush": "#000f0a",
        "lawngreen": "#8303ff",
        "lemonchiffon": "#000332",
        "lightblue": "#522719",
        "lightcoral": "#0f7f7f",
        "lightcyan": "#1f0000",
        "lightgoldenrodyellow": "#05052d",
        "lightgray": "#2c2c2c",
        "lightgreen": "#6f116f",
        "lightgrey": "#2c2c2c",
        "lightpink": "#00493e",
        "lightsalmon": "#005f85",
        "lightseagreen": "#df4d55",
        "lightskyblue": "#783105",
        "lightslategray": "#887766",
        "lightslategrey": "#887766",
        "lightsteelblue": "#4f3b21",
        "lightyellow": "#00001f",
        "lime": "#ff00ff",
        "limegreen": "#cd32cd",
        "linen": "#050f19",
        "magenta": "#00ff00",
        "maroon": "#7fff7f",
        "mediumaquamarine": "#993255",
        "mediumblue": "#ffff32",
        "mediumorchid": "#45a22c",
        "mediumpurple": "#6c8f24",
        "mediumseagreen": "#c34c8e",
        "mediumslateblue": "#849711",
        "mediumspringgreen": "#ff0565",
        "mediumturquoise": "#b72e33",
        "mediumvioletred": "#38eadd",
        "midnightblue": "#e6e68f",
        "mintcream": "#0a0005",
        "mistyrose": "#001b1e",
        "moccasin": "#001b4a",
        "navajowhite": "#002152",
        "navy": "#ffff7f",
        "oldlace": "#020a19",
        "olive": "#7f7f00",
        "olivedrab": "#9471dc",
        "orange": "#005a00",
        "orangered": "#00ba38",
        "orchid": "#258f29",
        "palegoldenrod": "#111755",
        "palegreen": "#670467",
        "paleturquoise": "#501111",
        "palevioletred": "#248f6c",
        "papayawhip": "#00102a",
        "peachpuff": "#002146",
        "peru": "#327a3c",
        "pink": "#003f34",
        "plum": "#225f22",
        "powderblue": "#4f1f19",
        "purple": "#7fff7f",
        "rebeccapurple": "#99cc66",
        "red": "#00ffff",
        "rosybrown": "#437070",
        "royalblue": "#be961e",
        "saddlebrown": "#74baec",
        "salmon": "#057f8d",
        "sandybrown": "#0b5b9f",
        "seagreen": "#d174a8",
        "seashell": "#000a11",
        "sienna": "#5fada1",
        "silver": "#3f3f3f",
        "skyblue": "#783114",
        "slateblue": "#95a332",
        "slategray": "#8f7f6f",
        "slategrey": "#8f7f6f",
        "snow": "#000505",
        "springgreen": "#ff0080",
        "steelblue": "#b97d4b",
        "tan": "#2d4b73",
        "teal": "#ff7f7f",
        "thistle": "#274027",
        "tomato": "#009cb8",
        "turquoise": "#bf1f2f",
        "violet": "#117d11",
        "wheat": "#0a214c",
        "white": "#000000",
        "whitesmoke": "#0a0a0a",
        "yellow": "#0000ff",
        "yellowgreen": "#6332cd",
    }),

});